; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:standardConfig]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
src_filter = 
	+<*>
	-<afg/afg.cpp>
	-<afg/simulation.cpp>
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -I include

monitor_speed = 115200
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.3
	adafruit/Adafruit RA8875@^1.4.4
	adafruit/Adafruit NeoPixel@^1.15.2
	impulseadventure/GUIslice@^0.17.2

